# - name : creating mongodb server
#   hosts: mongodb
#   become: yes
#   tasks:
#   - name: creating repo file
#     ansible.builtin.copy:
#       src: mongo.repo
#       dest: /etc/yum.repos.d/mongo.repo

#   - name: installing mongodb
#     ansible.builtin.package:
#       name: mongodb-org 
#       state: present

#   - name: starting the service
#     ansible.builtin.service:
#       name: mongod
#       state: started
#       enabled: yes
     
#   - name: allowing all
#     ansible.builtin.replace:
#       path: /etc/mongod.conf
#       regexp: 127.0.0.1
#       replace: 0.0.0.0

#   - name: starting the service
#     ansible.builtin.service:
#       name: mongod
#       state: started
#       enabled: yes

#     register: ec2_output

#   - name: printing
#     ansible.builtin.debug:
#       msg: "{{ ec2_output}}"

     
# # - name: setup mongodb server
# #   hosts: mongodb
# #   become: yes
# #   tasks:
# #   - name: copy mongodb repo
# #     ansible.builtin.copy:
# #       src: mongo.repo
# #       dest: /etc/yum.repos.d/mongo.repo

# #   - name: install mongodb server
# #     ansible.builtin.package:
# #       name: mongodb-org
# #       state: present
      
# #   - name: allow remote connections
# #     ansible.builtin.replace:
# #       path: /etc/mongod.conf
# #       regexp: '127.0.0.1'
# #       replace: '0.0.0.0'
  
# #   - name: start and enable service
# #     ansible.builtin.service:
# #       name: mongod
# #       state: started
# #       enabled: yes
  

- name: Creating MongoDB server
  hosts: mongodb
  become: yes
  tasks:

    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: Allow remote connections (replace bind IP)
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'

    - name: Restart and enable MongoDB service
      ansible.builtin.service:
        name: mongod
        state: restarted
        enabled: yes

    - name: Display MongoDB service status
      ansible.builtin.shell: systemctl status mongod | grep Active
      register: mongod_status

    - name: Print MongoDB service status
      ansible.builtin.debug:
        msg: "{{ mongod_status.stdout }}"
